[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.107.2",
    "gradio>=4.0.0",
    "pandas>=2.0.0",
    "openpyxl>=3.0.0",
    "python-dotenv>=1.0.0",
]
